/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125AuthRouteImport } from './routes/{-$locale}/auth'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as Char123LocaleChar125MainRouteRouteImport } from './routes/{-$locale}/main/route'
import { Route as Char123LocaleChar125MainIndexRouteImport } from './routes/{-$locale}/main/index'
import { Route as Char123LocaleChar125AuthLoginRouteImport } from './routes/{-$locale}/auth/login'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as Char123LocaleChar125MainLayoutRouteRouteImport } from './routes/{-$locale}/main/layout/route'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as Char123LocaleChar125MainLayoutUserIndexRouteImport } from './routes/{-$locale}/main/layout/user/index'
import { Route as Char123LocaleChar125MainLayoutWorkspacesWorkspaceIdIndexRouteImport } from './routes/{-$locale}/main/layout/workspaces/$workspaceId/index'

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AuthRoute =
  Char123LocaleChar125AuthRouteImport.update({
    id: '/auth',
    path: '/auth',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125MainRouteRoute =
  Char123LocaleChar125MainRouteRouteImport.update({
    id: '/main',
    path: '/main',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MainIndexRoute =
  Char123LocaleChar125MainIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125MainRouteRoute,
  } as any)
const Char123LocaleChar125AuthLoginRoute =
  Char123LocaleChar125AuthLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => Char123LocaleChar125AuthRoute,
  } as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125MainLayoutRouteRoute =
  Char123LocaleChar125MainLayoutRouteRouteImport.update({
    id: '/layout',
    path: '/layout',
    getParentRoute: () => Char123LocaleChar125MainRouteRoute,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125MainLayoutUserIndexRoute =
  Char123LocaleChar125MainLayoutUserIndexRouteImport.update({
    id: '/user/',
    path: '/user/',
    getParentRoute: () => Char123LocaleChar125MainLayoutRouteRoute,
  } as any)
const Char123LocaleChar125MainLayoutWorkspacesWorkspaceIdIndexRoute =
  Char123LocaleChar125MainLayoutWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/workspaces/$workspaceId/',
    path: '/workspaces/$workspaceId/',
    getParentRoute: () => Char123LocaleChar125MainLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/main': typeof Char123LocaleChar125MainRouteRouteWithChildren
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/main/layout': typeof Char123LocaleChar125MainLayoutRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/{-$locale}/auth/login': typeof Char123LocaleChar125AuthLoginRoute
  '/{-$locale}/main/': typeof Char123LocaleChar125MainIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/{-$locale}/main/layout/user': typeof Char123LocaleChar125MainLayoutUserIndexRoute
  '/{-$locale}/main/layout/workspaces/$workspaceId': typeof Char123LocaleChar125MainLayoutWorkspacesWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRouteWithChildren
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/main/layout': typeof Char123LocaleChar125MainLayoutRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/{-$locale}/auth/login': typeof Char123LocaleChar125AuthLoginRoute
  '/{-$locale}/main': typeof Char123LocaleChar125MainIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/{-$locale}/main/layout/user': typeof Char123LocaleChar125MainLayoutUserIndexRoute
  '/{-$locale}/main/layout/workspaces/$workspaceId': typeof Char123LocaleChar125MainLayoutWorkspacesWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/main': typeof Char123LocaleChar125MainRouteRouteWithChildren
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/main/layout': typeof Char123LocaleChar125MainLayoutRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/{-$locale}/auth/login': typeof Char123LocaleChar125AuthLoginRoute
  '/{-$locale}/main/': typeof Char123LocaleChar125MainIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/{-$locale}/main/layout/user/': typeof Char123LocaleChar125MainLayoutUserIndexRoute
  '/{-$locale}/main/layout/workspaces/$workspaceId/': typeof Char123LocaleChar125MainLayoutWorkspacesWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/main'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/{-$locale}/auth'
    | '/{-$locale}/'
    | '/{-$locale}/main/layout'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/{-$locale}/auth/login'
    | '/{-$locale}/main/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/{-$locale}/main/layout/user'
    | '/{-$locale}/main/layout/workspaces/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/{-$locale}/auth'
    | '/{-$locale}'
    | '/{-$locale}/main/layout'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/{-$locale}/auth/login'
    | '/{-$locale}/main'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/{-$locale}/main/layout/user'
    | '/{-$locale}/main/layout/workspaces/$workspaceId'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/main'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/{-$locale}/auth'
    | '/{-$locale}/'
    | '/{-$locale}/main/layout'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/{-$locale}/auth/login'
    | '/{-$locale}/main/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/{-$locale}/main/layout/user/'
    | '/{-$locale}/main/layout/workspaces/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  DemoPrismaRoute: typeof DemoPrismaRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/auth': {
      id: '/{-$locale}/auth'
      path: '/auth'
      fullPath: '/{-$locale}/auth'
      preLoaderRoute: typeof Char123LocaleChar125AuthRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/main': {
      id: '/{-$locale}/main'
      path: '/main'
      fullPath: '/{-$locale}/main'
      preLoaderRoute: typeof Char123LocaleChar125MainRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/main/': {
      id: '/{-$locale}/main/'
      path: '/'
      fullPath: '/{-$locale}/main/'
      preLoaderRoute: typeof Char123LocaleChar125MainIndexRouteImport
      parentRoute: typeof Char123LocaleChar125MainRouteRoute
    }
    '/{-$locale}/auth/login': {
      id: '/{-$locale}/auth/login'
      path: '/login'
      fullPath: '/{-$locale}/auth/login'
      preLoaderRoute: typeof Char123LocaleChar125AuthLoginRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/main/layout': {
      id: '/{-$locale}/main/layout'
      path: '/layout'
      fullPath: '/{-$locale}/main/layout'
      preLoaderRoute: typeof Char123LocaleChar125MainLayoutRouteRouteImport
      parentRoute: typeof Char123LocaleChar125MainRouteRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/main/layout/user/': {
      id: '/{-$locale}/main/layout/user/'
      path: '/user'
      fullPath: '/{-$locale}/main/layout/user'
      preLoaderRoute: typeof Char123LocaleChar125MainLayoutUserIndexRouteImport
      parentRoute: typeof Char123LocaleChar125MainLayoutRouteRoute
    }
    '/{-$locale}/main/layout/workspaces/$workspaceId/': {
      id: '/{-$locale}/main/layout/workspaces/$workspaceId/'
      path: '/workspaces/$workspaceId'
      fullPath: '/{-$locale}/main/layout/workspaces/$workspaceId'
      preLoaderRoute: typeof Char123LocaleChar125MainLayoutWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof Char123LocaleChar125MainLayoutRouteRoute
    }
  }
}

interface Char123LocaleChar125MainLayoutRouteRouteChildren {
  Char123LocaleChar125MainLayoutUserIndexRoute: typeof Char123LocaleChar125MainLayoutUserIndexRoute
  Char123LocaleChar125MainLayoutWorkspacesWorkspaceIdIndexRoute: typeof Char123LocaleChar125MainLayoutWorkspacesWorkspaceIdIndexRoute
}

const Char123LocaleChar125MainLayoutRouteRouteChildren: Char123LocaleChar125MainLayoutRouteRouteChildren =
  {
    Char123LocaleChar125MainLayoutUserIndexRoute:
      Char123LocaleChar125MainLayoutUserIndexRoute,
    Char123LocaleChar125MainLayoutWorkspacesWorkspaceIdIndexRoute:
      Char123LocaleChar125MainLayoutWorkspacesWorkspaceIdIndexRoute,
  }

const Char123LocaleChar125MainLayoutRouteRouteWithChildren =
  Char123LocaleChar125MainLayoutRouteRoute._addFileChildren(
    Char123LocaleChar125MainLayoutRouteRouteChildren,
  )

interface Char123LocaleChar125MainRouteRouteChildren {
  Char123LocaleChar125MainLayoutRouteRoute: typeof Char123LocaleChar125MainLayoutRouteRouteWithChildren
  Char123LocaleChar125MainIndexRoute: typeof Char123LocaleChar125MainIndexRoute
}

const Char123LocaleChar125MainRouteRouteChildren: Char123LocaleChar125MainRouteRouteChildren =
  {
    Char123LocaleChar125MainLayoutRouteRoute:
      Char123LocaleChar125MainLayoutRouteRouteWithChildren,
    Char123LocaleChar125MainIndexRoute: Char123LocaleChar125MainIndexRoute,
  }

const Char123LocaleChar125MainRouteRouteWithChildren =
  Char123LocaleChar125MainRouteRoute._addFileChildren(
    Char123LocaleChar125MainRouteRouteChildren,
  )

interface Char123LocaleChar125AuthRouteChildren {
  Char123LocaleChar125AuthLoginRoute: typeof Char123LocaleChar125AuthLoginRoute
}

const Char123LocaleChar125AuthRouteChildren: Char123LocaleChar125AuthRouteChildren =
  {
    Char123LocaleChar125AuthLoginRoute: Char123LocaleChar125AuthLoginRoute,
  }

const Char123LocaleChar125AuthRouteWithChildren =
  Char123LocaleChar125AuthRoute._addFileChildren(
    Char123LocaleChar125AuthRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125MainRouteRoute: typeof Char123LocaleChar125MainRouteRouteWithChildren
  Char123LocaleChar125AuthRoute: typeof Char123LocaleChar125AuthRouteWithChildren
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125MainRouteRoute:
      Char123LocaleChar125MainRouteRouteWithChildren,
    Char123LocaleChar125AuthRoute: Char123LocaleChar125AuthRouteWithChildren,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  DemoPrismaRoute: DemoPrismaRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
